language: objective-c
before_install:
  - brew tap caskroom/versions
  - brew cask install java8
  - export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
  - brew install ant
  - wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
  - unzip android-sdk_r24.4.1-macosx.zip
  - export ANDROID_HOME=$PWD/android-sdk-macosx
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter build-tools-23.0.3 --all --no-ui --force > /dev/null
  - echo yes | android update sdk --filter sysimg-23 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

script:
  - mkdir -p ./Plugins/Android/bridge/libs/
  - cp ./Plugins/Android/testfairy-sdk.jar ./Plugins/Android/bridge/libs/testfairy-sdk.jar
  - ant -f ./Plugins/Android/bridge/build.xml jar
  - zip -rp9 "TestFairySDK-${TRAVIS_TAG}-Unity.zip" Plugins -x Plugins/Android/bridge\*

deploy:
  provider: releases
  api_key:
    secure: DeCE3UiQBTxbuSskkBjMXkdXKvxiiJoPfvNVR874wNB0BEoAm+ZYMN+9XPuIlKfl0Fpd7XktaAvXEn2xK1FO7OXcJYPP1GZbyLwkzBm/YNmi4dHWr9BvPJzqdhLIEGw56pxuc2I6DOVys63rIZE9g1Ob68sm6ampNNfQfaXwk1s=
  file: TestFairySDK-${TRAVIS_TAG}-Unity.zip
  skip_cleanup: true
  on:
    tags: true

