language: node_js
node_js:
  - '14'

install:
  - npm -g i testfairy-unity-asset-packager
  - npm install

script:
  - ANDROID_SDK_VERSION=1.12.6
  - IOS_VERSION=1.28.7
  - mkdir -p Files/Android/
  - mkdir -p Files/iOS/
  - curl -s -L https://maven.testfairy.com/com/testfairy/testfairy-android-sdk/${ANDROID_SDK_VERSION}/testfairy-android-sdk-${ANDROID_SDK_VERSION}.aar -o Files/Android/testfairy-android-sdk.aar
  - curl -s -L https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-${IOS_VERSION}.zip -o  Files/iOS/TestFairySDK.zip
  - curl -s -L https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-${IOS_VERSION}.xcframework.zip -o  Files/iOS/TestFairySDK.xcframework.zip
  - unzip -o -d Files/iOS/ Files/iOS/TestFairySDK.zip
  - unzip -o -d Files/iOS/ Files/iOS/TestFairySDK.xcframework.zip
  - rm -f Files/iOS/TestFairySDK.zip
  - rm -f Files/iOS/TestFairySDK.xcframework.zip
  - node build.js static
  - zip -rp9 "TestFairySDK-${TRAVIS_TAG}-Unity.zip" Plugins
  - testfairy-unity-asset-packager --debug --prepend 'Assets/Plugins' --output TestFairySDK-${TRAVIS_TAG}-Unity.unitypackage --overwrite Plugins
  - sed "s/#import \"TestFairy.h\"/#import <TestFairy\/TestFairy.h>/g" Files/iOS/TestFairyUnityWrapper.m > Files/iOS/TestFairyUnityWrapper.m
  - node build.js xcframework
  - zip -rp9 "TestFairySDK-${TRAVIS_TAG}-Unity2021.zip" Plugins
  - testfairy-unity-asset-packager --debug --prepend 'Assets/Plugins' --output TestFairySDK-${TRAVIS_TAG}-Unity2021.unitypackage --overwrite Plugins
deploy:
  provider: releases
  api_key:
    secure: DeCE3UiQBTxbuSskkBjMXkdXKvxiiJoPfvNVR874wNB0BEoAm+ZYMN+9XPuIlKfl0Fpd7XktaAvXEn2xK1FO7OXcJYPP1GZbyLwkzBm/YNmi4dHWr9BvPJzqdhLIEGw56pxuc2I6DOVys63rIZE9g1Ob68sm6ampNNfQfaXwk1s=
  file:
    - TestFairySDK-${TRAVIS_TAG}-Unity.zip
    - TestFairySDK-${TRAVIS_TAG}-Unity.unitypackage
    - TestFairySDK-${TRAVIS_TAG}-Unity2021.zip
    - TestFairySDK-${TRAVIS_TAG}-Unity2021.unitypackage
  skip_cleanup: true
  on:
    tags: true
