language: node_js
node_js:
  - '12'

install:
  - npm -g i testfairy-unity-asset-packager

script:
  - ANDROID_SDK_VERSION=1.11.25
  - IOS_VERSION=1.26.6
  - rm -f Plugins/Android/testfairy-android-sdk.aar
  - curl -s -L https://bintray.com/testfairy/testfairy/download_file?file_path=testfairy%2Ftestfairy-android-sdk%2F${ANDROID_SDK_VERSION}%2Ftestfairy-android-sdk-${ANDROID_SDK_VERSION}.aar -o Plugins/Android/testfairy-android-sdk.aar
  - curl -s -L https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-${IOS_VERSION}-framework.zip -o  Plugins/iOS/TestFairySDK-framework.zip
  - unzip -o -d Plugins/iOS/ Plugins/iOS/TestFairySDK-framework.zip
  - rm Plugins/iOS/TestFairySDK-framework.zip
  - zip -rp9 "TestFairySDK-${TRAVIS_TAG}-Unity.zip" Plugins
  - testfairy-unity-asset-packager --debug --prepend 'Assets/Plugins' --output TestFairySDK-${TRAVIS_TAG}-Unity.unitypackage --overwrite Plugins
deploy:
  provider: releases
  api_key:
    secure: DeCE3UiQBTxbuSskkBjMXkdXKvxiiJoPfvNVR874wNB0BEoAm+ZYMN+9XPuIlKfl0Fpd7XktaAvXEn2xK1FO7OXcJYPP1GZbyLwkzBm/YNmi4dHWr9BvPJzqdhLIEGw56pxuc2I6DOVys63rIZE9g1Ob68sm6ampNNfQfaXwk1s=
  file:
    - TestFairySDK-${TRAVIS_TAG}-Unity.zip
    - TestFairySDK-${TRAVIS_TAG}-Unity.unitypackage
  skip_cleanup: true
  on:
    tags: true
